type: opt # single|window, maybe add opt
key: nsar #added to the csv names
evaluation: evaluation_user_based #evaluation|evaluation_last|evaluation_multiple
data:
  name: lastfm #added in the end of the csv names
  folder: data/lastfm/prepared/window/
  prefix: userid-timestamp-artid-artname-traid-traname.2
  type: hdf #hdf (if there is no type, the default is csv)

results:
  folder: results/opt/window/lastfm/nsar/

metrics:
- class: accuracy_multiple.Precision
  length: [5,10,15,20]
- class: accuracy_multiple.Recall
  length: [5,10,15,20]
- class: accuracy_multiple.MAP
  length: [5,10,15,20]
- class: accuracy.HitRate
  length: [5,10,15,20]
- class: accuracy.MRR
  length: [5,10,15,20]

algorithms:
- class: nsar.nsar.NSAR # small network, the TOP1 loss always outperformed other ranking losses, so we consider only it
  params: {num_epoch: 1, batch_size: 64, keep_pr: 0.25}
  params_opt:
    learning_rate: [ {from: 0.01, to: 0.001, in: 10, type: float32}, {from: 0.05, to: 0.01, in: 5, type: float32} ] # todo for their model as well?!!
    hidden_units: [50,100]
  key: nsar